urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('mall.views',
    url(r'^mall/(\d*)/store/(\d*)/$', 'store', {}, name="store"),
    url(r'^mall/(\d*)/floor/(\d*)/$', 'floor', {}, name="floor"),
    url(r'^mall/(\d*)/$', 'mall', {}, name="mall"),
    url(r'^add_store/(?P<viewmode>\w*)/$', 'add_store', {}, name="add_store"),
    url(r'^scrape_image/$', 'scrape_image', {}, name="scrape_image"),
    url(r'^do_crop/$', 'do_crop', {}, name="do_crop"),
    url(r'^remove_store/(?P<viewmode>\w*)/$', 'remove_store', {}, name="remove_store"),
    url(r'^move/(?P<itemtype>\w*)/$', 'move_item', {}, name="move_wishlistitem"),
    url(r'^move/(?P<itemtype>\w*)/(?P<viewmode>\w*)$', 'move_item', {}, name="move_store"),
)

urlpatterns += patterns('mall.wishlist_views',
    url(r'^add_wishlist/$', 'add_wishlist', {}, name='add_wishlist'),
    url(r'^add_to_wishlist/$', 'add_to_wishlist', {}, name='add_to_wishlist'),
    url(r'^remove_wishlistitem/$', 'remove_wishlistitem', {}, name="remove_wishlistitem"),
    url(r'^profile/(\d*)/wishlist/$', 'wishlist', {}, name="wishlist"),
    )

urlpatterns += patterns('mall.general_views',
    url(r'^register/$', 'register', {}, name="register"),
    url(r'^profile/(\d*)/$', 'profile', {}, name="profile"),
    url(r'^about/$', 'about', {}, name="about"),
    url(r'^login/$', 'login', name="login"),
    url(r'^logout/$', 'logout', name="logout"),
    )
urlpatterns += patterns('',
    (r'^ssmedia/store/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root':settings.STATIC_STORE_IMAGE_ROOT, 'show_indexes':True}),
    (r'^ssmedia/wishlist/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root':settings.STATIC_WISHLIST_IMAGE_ROOT, 'show_indexes':True}),
    (r'^ssmedia/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root':settings.STATIC_MEDIA_ROOT, 'show_indexes':True}),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/', include(admin.site.urls)),
    ('', 'mall.views.landing'),
)

mall/models.py
from django.db import models
from django.contrib.auth.models import User

class SSUser(User):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('U', 'Unknown'),
    )
    user = models.OneToOneField(User)
    bio = models.CharField(max_length=500)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default='U')

    @property
    def mall(self):
    	return Mall.objects.get(user=self)

class Mall(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=50)
    
    def __unicode__(self):
    	return self.name

class Domain(models.Model):
    domain = models.CharField(max_length=200)

    def __unicode__(self):
        return self.domain

class Store(models.Model):
    mall = models.ForeignKey(Mall)
    domain = models.ForeignKey(Domain)
    name = models.CharField(max_length=100)
    url = models.URLField(max_length=200)
    floor = models.IntegerField()
    position = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    tags = models.CharField(max_length=1000)
    is_private = models.BooleanField(default=False)
    
    def __unicode__(self):
    	return self.name
    
class StoreImages(models.Model):
    user = models.ForeignKey(User)
    store = models.ForeignKey(Store)
    path = models.CharField(max_length=1000)
    width = models.IntegerField()
    height = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.path
    
class Wishlist(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    date_added = models.DateTimeField(auto_now_add=True)
    is_private = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

class WishlistItem(models.Model):
    wishlist = models.ForeignKey(Wishlist)
    domain = models.ForeignKey(Domain)
    url = models.CharField(max_length=2000)
    tags = models.CharField(max_length=1000)
    position = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)
    is_private = models.BooleanField(default=False)

    def __unicode__(self):
        return self.url

class WishlistImages(models.Model):
    user = models.ForeignKey(User)
    wishlistitem = models.ForeignKey(WishlistItem)
    path = models.CharField(max_length=1000)
    width = models.IntegerField()
    height = models.IntegerField()
    date_added = models.DateTimeField(auto_now_add=True)

mall/forms.py
import re
from django import forms
from django.forms import ModelForm
from django.forms.widgets import RadioSelect
from django.contrib.auth.models import User
from models import Store

class RegisterForm(forms.Form):
    first_name = forms.CharField(max_length=20)
    last_name  = forms.CharField(max_length=20)
    email      = forms.EmailField()
    password   = forms.CharField(max_length=20, widget=forms.PasswordInput)
    mall_name  = forms.CharField(max_length=50)
    
    def create_user(self):
    	data = self.cleaned_data
    	email = data['email']
    	password = data['password']
    	first_name = data['first_name']
    	last_name = data['last_name']
    		
    	
    	username = re.sub('\.', '_', (re.sub('@', '_', email)))
    	user = User.objects.create_user(username, email, password)
    	user.first_name = first_name
    	user.last_name = last_name
    	
    	user.save()
    	return user
   
class AddStoreForm(forms.Form):
    name = forms.CharField(max_length=100)
    url = forms.CharField(max_length=200)
    tags = forms.CharField(max_length=1000, required=False)
    is_private = forms.BooleanField()

class AddWishlistForm(forms.Form):
    name = forms.CharField(max_length=100)
    is_private = forms.BooleanField()
    description = forms.CharField(max_length=1000, required=False)
    
class WishlistItemForm(forms.Form):
    url = forms.CharField(max_length=2000)
    tags = forms.CharField(max_length=1000, required=False)
    is_private = forms.BooleanField()

mall/views.py
import json, re, subprocess, traceback

from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template.loader import render_to_string
from django.contrib import auth
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from mall.models import Store, StoreImages, Mall, SSUser, Wishlist, WishlistItem, Domain
from mall.forms import RegisterForm, AddStoreForm
from mall.wishlist_views import _getwishlistHTML, _zipWishlistImages
from utils import ImageScraper, imageutils, urlutils, sysutils
import MyGlobals

def landing(request):
    ctx_dict = {
    	'request':request,
    	'ssmedia':'/ssmedia',
    }
    return render_to_response('landing.html', ctx_dict, context_instance=RequestContext(request))

def mall(request, mall_id):
    form = AddStoreForm()
    ctx_dict = _getmall(request, mall_id)
    ctx_dict.update({
    	'form':form,
    	'request':request,
    	'ssmedia':'/ssmedia',
        'MyGlobals':MyGlobals
    })
    return render_to_response("mall.html", ctx_dict, context_instance=RequestContext(request))

def _getmall(request, mall_id):
    mall = Mall.objects.get(pk=mall_id)
    is_owner = (request.user == mall.user)
    if is_owner:
        stores_list = Store.objects.filter(mall__id=mall_id).order_by('floor', 'position')
    else:
        stores_list = Store.objects.filter(mall__id=mall_id, is_private=False).order_by('floor', 'position')        
    mall_dict = _zipStoreInfo(stores_list)
    if is_owner:
        mall_dict = _zipFloorInfo(mall_dict)

    ctx_dict = {
        'is_owner':is_owner,
        'mall_dict':mall_dict,
        'mall_id':mall_id,
        'mall':mall
        }
    return ctx_dict

def _getmallHTML(request, mall_id):
    mall = Mall.objects.get(pk=mall_id)
    ctx_dict = _getmall(request, mall_id)
    html = render_to_string("mall_snippet.html", ctx_dict, context_instance=RequestContext(request))
    return html

def _zipFloorInfo(mall_dict):
    # add extra floor (next expansion)
    all_floors = mall_dict.keys()
    if not all_floors:
        mall_dict[0] = {}
    else:
        all_floors.sort()
        mall_dict[all_floors[-1]+1] = {}
    return mall_dict    
    
def _zipStoreInfo(stores_list):
    mall_dict = {}
    stores_list = _zipStoreImages(stores_list)
    for storetup in stores_list:
        try:
            floor_dict = mall_dict[storetup[0].floor]
        except:
            floor_dict = {}
            mall_dict[storetup[0].floor] = floor_dict

        try:
            floor_dict['stores_list'].append(storetup)
        except:
            floor_dict['stores_list'] = [storetup]

    return mall_dict

def _zipStoreImages(stores):
    stores_list = []
    for store in stores:
        try:
            si = StoreImages.objects.get(store=store)
        except:
            si = None

        try:
            stores_list.append((store, si))
        except:
            stores_list = [(store, si)]

    return stores_list
    
def floor(request, mall_id, floor_id):
    form = AddStoreForm()
    ctx_dict = _getfloor(request, mall_id, floor_id)
    ctx_dict.update({
        'form':form,
    	'request':request,
    	'ssmedia':'/ssmedia',
        'MyGlobals':MyGlobals
    })
    return render_to_response("floor.html", ctx_dict, context_instance=RequestContext(request))

def _getfloor(request, mall_id, floor_id):
    mall = Mall.objects.get(pk=mall_id)
    is_owner = (request.user == mall.user)
    if is_owner:
        all_stores = Store.objects.filter(mall__id=mall_id, floor=floor_id).order_by('position')
    else:
        all_stores = Store.objects.filter(mall__id=mall_id, floor=floor_id, is_private=False).order_by('position')
        
    try:
        stores_list = _zipStoreInfo(all_stores)[int(floor_id)]['stores_list']
    except Exception, e:
        stores_list = []

    ctx_dict = {
        'mall':mall,
        'stores_list':stores_list,
        'floor_id':floor_id,
        'viewmode':'floor'
        }
    return ctx_dict

def _getfloorHTML(mall_id, floor_id):
    ctx_dict = _getfloor(mall_id, floor_id)
    html = render_to_string("floor_snippet.html", ctx_dict, context_instance=RequestContext(request))
    return html
    
def store(request, mall_id, store_id):
    store = Store.objects.get(pk=store_id)
    is_owner = (request.user == store.mall.user)
    (store, storeimg) = _zipStoreImages([store])[0]
    if is_owner:
        wishlistitems = WishlistItem.objects.filter(wishlist__user=request.user, domain_id=store.domain.id)
        wishlistitems = _zipWishlistImages(wishlistitems)
    else:
        wishlistitems = {}
    ctx_dict = {
        'is_owner':is_owner,
        'store':store,
        'storeimg':storeimg,
        'wishlistitems':wishlistitems,
    	'request':request,
    	'ssmedia':'/ssmedia',
        'MyGlobals':MyGlobals
    }
    return render_to_response("store.html", ctx_dict, context_instance=RequestContext(request))
    
def scrape_image(request):
    url = request.POST.get('url')
    scrape_for = request.POST.get('type')
    start_index = int(request.POST.get('start_index', 0))
    uid = request.user.id

    imgHTML = ''
    filename = urlutils.getScrapedImageFilename()
    if scrape_for == 'store':
        filedir = MyGlobals.STOREIMG_ROOT % { 'uid':uid }
        imgpath = MyGlobals.STOREIMG_ROOT_SRV % { 'uid':uid }
    elif scrape_for == 'wishlist':
        filedir = MyGlobals.WISHLISTIMG_ROOT % { 'uid':uid }
        imgpath = MyGlobals.WISHLISTIMG_ROOT_SRV % { 'uid':uid }

    width = '??'
    height = '??'
    try:
        (filedir, filename, imgindex, (w,h)) = ImageScraper.getImagesFromURL(url,
                                                                             filedir=filedir,
                                                                             filename=filename,
                                                                             start_index=start_index)
        if filename:
            try:
                (filedir, filename) = imageutils.resize_image(filedir, filename)
            except Exception, e:
                print "unable to resize image: %s" % str(e)

            try:
                width = str(w)
                height = str(h)
            except:
                pass
                
            ctx_dict = {
                'width':width,
                'height':height,
                'imgpath':imgpath,
                'filename':filename
                }
            imgHTML = render_to_string("select_img_snippet.html", ctx_dict, context_instance=RequestContext(request))
        else:
            raise Exception("no image to scrape")
        status = 'ok'
    except Exception, e:
        print "unable to scrape image: %s; %s" % (str(e), traceback.print_exc())
        filename = None
        imgpath = None
        # if there's an issue, move scrape to next image to prevent cycle
        imgindex = -1 if (e == "no image to scrape")  else start_index+1
        status = 'complete' if (e == "no image to scrape") else 'error'

    response = {
        'status':status,
        'filename':filename,
        'imgpath':imgpath,
        'imgindex':imgindex,
        'width':width,
        'height':height,
        'imgHTML':imgHTML
        }
    return HttpResponse(json.dumps(response), mimetype="application/json")

def do_crop(request):
    uid = request.user.id
    filename = request.POST.get('filename')
    width = request.POST.get('width')
    height = request.POST.get('height')
    crop_for = request.POST.get('type')
    crop_x1 = int(float(request.POST.get('crop_x1')))
    crop_y1 = int(float(request.POST.get('crop_y1')))
    crop_x2 = int(float(request.POST.get('crop_x2')))
    crop_y2 = int(float(request.POST.get('crop_y2')))
    cropbox = [crop_x1, crop_y1, crop_x2, crop_y2]

    if crop_for == 'store':
        filedir = MyGlobals.STOREIMG_ROOT % { 'uid':uid }
        imgpath = MyGlobals.STOREIMG_ROOT_SRV % { 'uid':uid }
    elif crop_for == 'wishlist':
        filedir = MyGlobals.WISHLISTIMG_ROOT % { 'uid':uid }
        imgpath = MyGlobals.WISHLISTIMG_ROOT_SRV % { 'uid':uid }
    
    try:
        (filedir, filename) = imageutils.crop_image(filedir, filename, cropbox)
        status = 'ok'
    except Exception, e:
        print "unable to do crop: %s" % str(e)
        status = 'error'
        filename = ''
        imgpath = ''

    response = {
        'width':width,
        'height':height,
        'status':status,
        'filename':filename,
        'imgpath':'%s/%s'%(imgpath, filename)
        }
    return HttpResponse(json.dumps(response), mimetype="application/json")
    
def add_store(request, viewmode):
    uid = request.user.id
    mallid = request.POST.get('mallid')
    name = request.POST.get('name')
    url = request.POST.get('url')
    tags = request.POST.get('tags')
    is_private = request.POST.get('is_private', 'off')
    filename = request.POST.get('filename')
    width = int(request.POST.get('width'))
    height = int(request.POST.get('height'))

    addStoreFormHTML = ''
    mallHTML = ''
    success_msg = ''
    error_msg = ''
    try:
        floor = 0
        pos = len(Store.objects.filter(mall__id=mallid, floor=0).order_by('position'))
        dom = urlutils.getDomainFromUrl(url)
        (domain, created) = Domain.objects.get_or_create(domain=dom)
        new_store = Store.objects.create(mall=Mall.objects.get(pk=mallid),
                                         name=name,
                                         url=url,
                                         floor=floor,
                                         position=pos,
                                         tags=tags,
                                         domain=domain,
                                         is_private=is_private)
        new_store.save()
    except Exception, e:

mall/templates/add_store_snippet.html
<div class="addstoretitle overlaytitle">
  add a store
</div>
<div class="addstoreformcontainer overlayformcontainer">
  <div class="addstorebreadcrumbs overlaybreadcrumbs breadcrumbs">
    <div class="breadcrumb1 currstep">1. add store info</div>
    <div class="breadcrumb2">2. select store image</div>    
    <div class="breadcrumb3">3. crop store image</div>    
  </div>
  <form id="addstoreform">    
    <div class="addstorestep1 overlaystep1">
      <table>
	<tr>
	  <td colspan="2">{% for error in form.url.errors %}{{error}}{% endfor %}</td>
	</tr>
	<tr>
	  <td class="addstorelabel overlaylabel"><label for="id_url"> Store URL </td>
	  <td class="addstoreinput overlayinput">
	    <input type="url" id="id_url" name="url" maxlength="200" placeholder="your store url" />
	    <span class="statusicon">ok</span>	  
	  </td>
	</tr>
	
	<tr>
	  <td colspan="2">{% for error in form.name.errors %}{{error}}{% endfor %}</td>
	</tr>
	<tr>
	  <td class="addstorelabel overlaylabel"><label for="id_name"> Store Name </td>
	  <td class="addstoreinput overlayinput">
	    <input type="text" id="id_name" name="name" maxlength="100" placeholder="name of the store" />	  
	  </td>
	</tr>
	
	<tr>
	  <td colspan="2">{% for error in form.tags.errors %}{{error}}{% endfor %}</td>
	</tr>
	<tr>
	  <td class="addstorelabel overlaylabel"><label for="id_tags"> Tags </td>
	  <td class="addstoreinput overlayinput">
	    <input type="text" id="id_tags" name="tags" maxlength="1000" placeholder="categories for this store" />	  
	  </td>
	</tr>
	
	<tr>
	  <td class="addstorelabel overlaylabel"><label for="id_is_private"> Keep store private? </td>
	  <td class="addstoreinput overlayinput">{{form.is_private}}</td>
	</tr>
      </table>
      <div class="submitcontainer">
	<div class="buttontext backbutton close">cancel</div>
	<input type="button" class="button tinybutton step1button" value="Continue"/>
      </div>      
    </div>
    <div class="addstorestep2 overlaystep2">
      <div class="loadingicon">
	<span style="line-height:60px;">loading ...</span>
	<img src="/ssmedia/images/loading_big.gif"></img>
      </div>
      <div class="addstoreslidedown overlayslidedown">
	<div class="addstoreimages overlayimages noimages">
	  <!--img class="visibleimage" src="/ssmedia/store/1/1354086809.jpg" id="visibleimage">
	      <img class="hiddenimage" src="/ssmedia/store/1/1354086812.jpg"-->
	</div>
	<div class="submitcontainer">	
	  <div class="buttontext backbutton back2button">back</div>
	  <input type="button" class="button tinybutton step2button selectbutton" value="select" />
	</div>	  
      </div>
    </div>      
    <div class="addstorestep3 overlaystep3">
      <div class="addstorecropcontainer overlaycropcontainer dotthinborder">
	<div class="overlaycropimg">	
	  <input type="hidden" id="crop_x1" name="crop_x1" />  
	  <input type="hidden" id="crop_y1" name="crop_y1" />  
	  <input type="hidden" id="crop_x2" name="crop_x2" />  
	  <input type="hidden" id="crop_y2" name="crop_y2" />
	</div>	  
	<input type="button" class="button tinybutton cropbutton" value="crop" />
      </div>
      <div class="submitcontainer">
	<div class="buttontext backbutton back3button">back</div>
	<input type="button" class="button tinybutton addstorebutton" value="Add Store">
      </div>
    </div>
  </form>
</div>

mall/templates/add_wishlist_snippet.html
<div class="addwishlisttitle overlaytitle">
  add wishlist  
</div>
<div class="addwishlistformcontainer overlayformcontainer">
  <form id="addwishlistform"> {% csrf_token %}
    <table>
      <tr>
	<td colspan="2">{% for error in add_wl_form.name.errors %}{{error}}{% endfor %}</td>
      </tr>
      <tr>
	<td class="overlaylabel"><label for="id_name"> Wishlist name: </td>
	<td class="overlayinput"><input id="id_name" type="text" name="name" maxlength="200" placeholder="your wishlist name"></td>
      </tr>
      
      <tr>
	<td colspan="2">{% for error in add_wl_form.description.errors %}{{error}}{% endfor %}</td>
      </tr>
      <tr>
	<td class="overlaylabel"><label for="id_tags"> Wishlist Description </td>
	<td class="overlayinput">{{add_wl_form.description}}</td>
      </tr>

      <tr>
	<td class="overlaylabel"><label for="id_is_private"> Keep wishlist private? </td>
	<td class="overlayinput">{{add_wl_form.is_private}}</td>
      </tr>
    </table>
    <div class="addwishlistsubmit overlaysubmit">
      <input id="addwishlistbutton" type="button" class="button tinybutton addwishlistbutton" value="Add Wishlist">
    </div>  
  </form>
</div>

mall/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet" href="{{ssmedia}}/css/style.css" />
  <link rel="stylesheet" href="{{ssmedia}}/css/header.css" />
  <link rel="stylesheet" href="{{ssmedia}}/css/footer.css" />
  <link rel="stylesheet" href="{{ssmedia}}/css/button.css" />
  {% block css %}
  {% endblock %}
  <script type="text/javascript" src="{{ssmedia}}/js/common.js"></script>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
  <script type="text/javascript" src="{{ssmedia}}/js/jquery-ui-1.9.1.custom.min.js"></script>
  {% block js %}
  {% endblock %}

  <title>{% block title %}shop square{% endblock %}</title>
</head>

<body>
  {% block shield %}  
  <div id="shield">
  </div>
  {% endblock %}  

  <div id="header">
    {% block header %}
      {% include "header.html" %}
    {% endblock %}
  </div>
  
  <div id="content">
      {% block content %}
      {% endblock %}
  </div>
  
  <div id="footer">
    {% block footer %}
      {% include "footer.html" %}
    {% endblock %}
  </div>
</body>
</html>

mall/templates/floor.html
{% extends "base.html" %}

{% block title %}shop square - mall - floor{% endblock %}
{% block css %}
<link rel="stylesheet" href="{{ssmedia}}/css/mall.css" type="text/css"/>
<link rel="stylesheet" href="{{ssmedia}}/css/shared_mall_wishlist.css" type="text/css"/>
<link rel="stylesheet" href="{{ssmedia}}/css/overlay.css" type="text/css"/>
<link rel="stylesheet" href="{{ssmedia}}/css/jquery.Jcrop.min.css" type="text/css"/>
{% endblock %}
{% block js %}
<script type="text/javascript">
//<![CDATA[
var addStoreURL = "{% url add_store 'floor' %}";
var removeStoreURL = "{% url remove_store 'floor' %}";
var moveStoreURL = "{% url move_store 'store' 'floor' %}";
var scrapeImageURL = "{% url scrape_image %}";
var doCropURL = "{% url do_crop %}";
var viewmode = "floor";
var mallid = '{{mall.id}}';
var floorid = '{{floor_id}}';
var addformtrigger;
var imageScrapeCount;  
//]]>
</script>
<script type="text/javascript" src="{{ssmedia}}/js/overlay.js"></script>
<script type="text/javascript" src="{{ssmedia}}/js/store.js"></script>
<script type="text/javascript" src="{{ssmedia}}/js/jquery.Jcrop.min.js"></script>
<script type="text/javascript" src="{{ssmedia}}/js/jquery.tools.min.js"></script>
{% endblock %}

{% block content %}
  <div id="addstoreoverlay" class="addstoreoverlay thinborder overlay">
    {% include 'add_store_snippet.html' %}
  </div>
  <div id="workspace">
    <div class="floorname workspacetitle">floor {{floor_id}}</div>
    <div class="successMsg success"></div>
    <div class="errorMsg error"></div>
    <div id="breadcrumbs" class="breadcrumbs">
      <a href="{% url mall mall.id %}">mall</a> &gt;
      <span>floor {{floor_id}}</span>    
    </div>
    <div class="addstoreicon thinborder icontext overlayicon" rel="#addstoreoverlay">+ store</div>
    <div id="floor">
      {% include "floor_snippet.html" %}      
    </div>
  </div>
{% endblock %}

mall/templates/footer.html
<div id="footer-content">
	<a href="/about/">about</a>
	<a href="/">footer link2</a>
</div>

mall/templates/header.html
<div id="header-content">
  <div id="header-logo">
    <a href="/">SHOP SQUARE</a>
  </div>
  <div id="header-user-links">
    <ul id="header-nav">
    {% if request.user.is_authenticated %}
    <li>Welcome, {{request.user.first_name}}</li>
    <li><a href="{% url profile request.user.id  %}">profile</a></li>
    <li><a href="{% url wishlist request.user.id %}">wishlist</a></li>
    <li><a href="/mall/{{request.user.ssuser.mall.id}}/">mall</a></li>
    <li><a href="/logout/">log out</a></li>
    {% else %}
    <li><a href="/login/">log in</a></li>
    <li><a href="/register/">sign up</a></li>
    {% endif %}
    </ul>
  </div>
</div>

mall/templates/landing.html
{% extends "base.html" %}

{% block title %}shop square - landing{% endblock %}
{% block css %}
<link rel="stylesheet" href="{{ssmedia}}/css/landing.css"/>
{% endblock %}

{% block content %}
{% endblock %}

mall/templates/login.html
{% extends "base.html" %}

{% block css %}
<link rel="stylesheet" href="{{ssmedia}}/css/login.css" type="text/css"/>
{% endblock %}
{% block js %}{% endblock %}

{% block title %}shop square - login{% endblock %}


{% block content %}
<div id="workspace">
  <div class="workspacetitle">log in</div>

  <div class="loginformcontainer thinborder">  
    <form id="loginform" action="/login/" method="POST">{% csrf_token %}
      <table>
	<tr>
	  <td></td>	  
	  <td class="error">{% if form.email.errors %}{{ form.email.errors }}{% endif %}</td>
	</tr>
	<tr>
	  <td class="loginlabel"><label for="id_email">Email</label></td>
	  <td class="logininput"><input type="text" name="email" value="" id="email" size="30"></td>
	</tr>	  

	<tr>
	  <td></td>
	  <td class="erro">{% if form.password.errors %}{{ form.password.errors }}{% endif %}</td>
	</tr>
	<tr>
	  <td class="loginlabel"><label for="id_password">Password</label></td>
	  <td class="logininput"><input type="password" name="password" value="" id="password" size="30"></td>
	</tr>
      </table>

      <div class="loginsubmitcontainer">
	<input type="submit" class="button tinybutton" value="Log In" />
      </div>	  
    </form>
  </div>
</div>    
{% endblock %}

mall/templates/profile.html
{% extends "base.html" %}

{% block title %}shop square - profile{% endblock %}

{% block content %}
Profile.<br>
Bio {{request.user.ssuser.bio}}<br>
Gender {{request.user.ssuser.gender}}<br>
{% endblock %}

mall/templates/select_img_snippet.html
<div class="selectimgcontainer">
  <div class="selectimgsize">{{width}} x {{height}}</div>  
  <img src="{{imgpath}}/{{filename}}">  
</div>